[package]
name = "arb"
version = "0.1.0"
authors = ["Adrian Kumpf <adrian.kumpf@posteo.de>"]
license = "MIT"
build = "build.rs"

[lib]
name = "arb"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.2"
arb = { git = "https://github.com/adriankumpf/abacom-relay-board", tag = 'v0.2.1' }
